apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    type: local
    app: poc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/V1
  storageClassName: default