kind: PersistentVolume
apiVersion: v1
metadata:
  name: test-pvc 
  labels:
    type: local
spec:
  storageClassName: manual 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/test-pvc" 